name: Scrape New Episodes

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scraper

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute Script
        run: |
          OUTPUT = $(python newest_episode_scraper.py | tail -1) &&
          echo "::set-output name=OUTPUT::$OUTPUT"
        env:
          CONTENTFUL_ENVIRONMENT: master
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
          CONTENTFUL_PAT: ${{ secrets.CONTENTFUL_PAT }}
          PREMIUM_RSS_FEED: ${{ secrets.PREMIUM_RSS_FEED }}

      - name: Run Build Client Action
        if: steps.main.outputs.OUTPUT > 0
        run: echo "NEED TO RUN BUILD CLIENT ACTION"

      - name: Do Nothing
        if: steps.main.outputs.OUTPUT == 0
        run: echo "NOTHING NEEDS TO BE DONE"
